apiVersion: v1
kind: Service
metadata:
  name: self-service-user
  namespace: ${namespace}
  labels:
    app: self-service-user
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: self-service-user